name: Android CI

on:
  push:
    branches: 
      - main
      - staging
      - dev
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Write permission for Gradlew
      run: chmod +x ./gradlew 
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build dev Application
      run: ./gradlew buildDevDebug
